---
- name: List available network offerings
  hosts: localhost
  collections:
    - ngine_io.cloudstack
  tasks:
    - name: List network offerings
      ngine_io.cloudstack.cs_network_offering_info:
        api_key: "{{ api_key }}"
        api_secret: "{{ api_secret }}"
        api_url: "{{ api_url }}"
      register: network_offerings

    - name: Debug network offerings
      debug:
        var: network_offerings

