---
- name: Set up CloudStack environment
  hosts: localhost
  collections:
    - ngine_io.cloudstack

  vars:
    num_subnets: 3
    num_vms: 1
    network_name: "network01.compfinity.local"
    subnet_name_prefix: "subnet"
    vm_name_prefix: "vm"
    api_url: "{{ lookup('env', 'API_URL') }}"
    api_key: "{{ lookup('env', 'API_KEY') }}"
    api_secret: "{{ lookup('env', 'SECRET_KEY') }}"
    zone: "us-east-1b"
    vpc_offering: "Default VPC offering"
    subnet_network_offering: "Offering for Isolated Vpc networks with Source Nat service enabled"

  tasks:
    - name: Create a new VPC
      ngine_io.cloudstack.cs_vpc:
        name: "{{ network_name }}"
        display_text: "Compfinity VPC"
        cidr: "10.0.0.0/16"
        vpc_offering: "{{ vpc_offering }}"
        zone: "{{ zone }}"
        api_key: "{{ api_key }}"
        api_secret: "{{ api_secret }}"
        api_url: "{{ api_url }}"
      register: vpc


    - name: Create multiple subnets within the VPC
      loop: "{{ range(1, num_subnets + 1) | list }}"
      ngine_io.cloudstack.cs_network:
        name: "{{ subnet_name_prefix }}{{ '%02d' | format(item) }}.compfinity.local"
        display_text: "Compfinity Subnet {{ item }}"
        network_offering: "{{ subnet_network_offering }}"
        vpc: "{{ vpc.id }}"
        zone: "{{ zone }}"
        api_key: "{{ api_key }}"
        api_secret: "{{ api_secret }}"
        api_url: "{{ api_url }}"
      register: subnets

    - name: Deploy multiple VMs within the created subnets
      loop: "{{ range(1, num_vms + 1) | list }}"
      ngine_io.cloudstack.cs_instance:
        name: "{{ vm_name_prefix }}{{ '%02d' | format(item) }}"
        service_offering: "Small Instance"
        template: "Ubuntu 22.04 LTS"
        zone: "{{ zone }}"
        network: "{{ subnets.results[0].id }}"  # Using the first subnet for simplicity
        api_key: "{{ api_key }}"
        api_secret: "{{ api_secret }}"
        api_url: "{{ api_url }}"
      register: vm_results

    - name: Assign a public IP to each VM
      loop: "{{ vm_results.results }}"
      ngine_io.cloudstack.cs_ip_address:
        vpc: "{{ vpc.id }}"
        api_key: "{{ api_key }}"
        api_secret: "{{ api_secret }}"
        api_url: "{{ api_url }}"
      register: public_ips

    - name: Add public IP to each VM
      loop: "{{ vm_results.results | zip(public_ips.results) | list }}"
      ngine_io.cloudstack.cs_staticnat:
        state: present
        ip_address: "{{ item.1.ipaddress }}"
        vm: "{{ item.0.id }}"
        api_key: "{{ api_key }}"
        api_secret: "{{ api_secret }}"
        api_url: "{{ api_url }}"

