---
- name: Print a message on the target VM
  hosts: vm_group
  become: yes
  vars:
    ansible_user: "{{ lookup('env', 'VM_USERNAME') }}"
    ansible_password: "{{ lookup('env', 'VM_PASSWORD') }}"
    ansible_ssh_common_args: "{{ lookup('env', 'ANSIBLE_SSH_COMMON_ARGS') | default('') }}"
  tasks:
    - name: Print a message
      ansible.builtin.debug:
        msg: "Hello from Ansible! This message is printed on {{ inventory_hostname }}"

