---
- name: Create multiple VMs in CloudStack
  hosts: localhost
  gather_facts: no
  collections:
    - ngine_io.cloudstack
  vars:
    api_key: "{{ cloudstack_api_key }}"
    secret_key: "{{ cloudstack_secret_key }}"
    zone: "{{ cloudstack_zone }}"
    template: "{{ cloudstack_template }}"
    service_offering: "{{ cloudstack_service_offering }}"
    network: "{{ cloudstack_network }}"
    base_name: "{{ vm_base_name }}"
    vm_count: "{{ vm_count }}"

  tasks:
    - name: Create VMs
      ngine_io.cloudstack.cs_instance:
        api_key: "{{ api_key }}"
        secret_key: "{{ secret_key }}"
        zone: "{{ zone }}"
        template: "{{ template }}"
        service_offering: "{{ service_offering }}"
        network: "{{ network }}"
        name: "{{ base_name }}{{ item }}"
        display_name: "{{ base_name }}{{ item }}"
      loop: "{{ range(1, vm_count + 1) | list }}"

