---
- name: Set up CloudStack environment
  hosts: localhost
  collections:
    - ngine_io.cloudstack

  vars:
    num_vms: 3
    network_name: "network01.example.local"
    subnet_name: "subnet01.example.local"
    vm_name_prefix: "vm"
    api_url: "{{ lookup('env', 'API_URL') }}"
    api_key: "{{ lookup('env', 'API_KEY') }}"
    api_secret: "{{ lookup('env', 'SECRET_KEY') }}"
    zone: "us-east-1b"
    api_verify_ssl_cert: false

  tasks:
    - name: Create a new network
      ngine_io.cloudstack.cs_network:
        name: "{{ network_name }}"
        display_text: "Example Network"
        network_offering: "DefaultIsolatedNetworkOfferingWithSourceNatService"
        zone: "{{ zone }}"
        api_key: "{{ api_key }}"
        api_secret: "{{ api_secret }}"
        api_url: "{{ api_url }}"
      register: network

    - name: Create a new subnet
      ngine_io.cloudstack.cs_vpc:
        name: "{{ subnet_name }}"
        display_text: "Example Subnet"
        cidr: "10.0.0.0/16"
        network_domain: "example.local"
        zone: "{{ zone }}"
        api_key: "{{ api_key }}"
        api_secret: "{{ api_secret }}"
        api_url: "{{ api_url }}"
      register: subnet

    - name: Deploy multiple VMs
      loop: "{{ range(1, num_vms + 1) | list }}"
      ngine_io.cloudstack.cs_instance:
        name: "{{ vm_name_prefix }}{{ '%02d' | format(item) }}.example.local"
        service_offering: "Small Instance"
        template: "Ubuntu 22.04 LTS"
        zone: "{{ zone }}"
        network: "{{ network.id }}"
        ip_address: auto
        api_key: "{{ api_key }}"
        api_secret: "{{ api_secret }}"
        api_url: "{{ api_url }}"
      register: vm_results

    - name: Assign a public IP to each VM
      loop: "{{ vm_results.results }}"
      ngine_io.cloudstack.cs_ip_address:
        vpc: "{{ subnet.id }}"
        api_key: "{{ api_key }}"
        api_secret: "{{ api_secret }}"
        api_url: "{{ api_url }}"
      register: public_ips

    - name: Add public IP to each VM
      loop: "{{ vm_results.results | zip(public_ips.results) | list }}"
      ngine_io.cloudstack.cs_staticnat:
        state: present
        ip_address: "{{ item.1.ipaddress }}"
        vm: "{{ item.0.id }}"
        api_key: "{{ api_key }}"
        api_secret: "{{ api_secret }}"
        api_url: "{{ api_url }}"

