---
- name: Set up CloudStack environment
  hosts: localhost
  collections:
    - ngine_io.cloudstack

  vars:
    num_vms: 3
    network_name: "wnc-network01.wezeshanet.local"
    subnet_name: "wnc-subnet01.wezeshanet.local"
    vm_name_prefix: "wnc-vm"

  tasks:
    - name: Create a new network
      ngine_io.cloudstack.cs_network:
        name: "{{ network_name }}"
        display_text: "Wezeshanet Network"
        network_offering: "DefaultIsolatedNetworkOfferingWithSourceNatService"
        zone: "Maryland"
        api_key: "{{ lookup('env', 'CLOUDSTACK_API_KEY') }}"
        secret_key: "{{ lookup('env', 'CLOUDSTACK_SECRET_KEY') }}"
        api_url: "{{ lookup('env', 'CLOUDSTACK_API_URL') }}"
      register: network

    - name: Create a new subnet
      ngine_io.cloudstack.cs_vpc:
        name: "{{ subnet_name }}"
        display_text: "Wezeshanet Subnet"
        cidr: "10.0.0.0/16"
        network_domain: "wezeshanet.local"
        zone: "Maryland"
        api_key: "{{ lookup('env', 'CLOUDSTACK_API_KEY') }}"
        secret_key: "{{ lookup('env', 'CLOUDSTACK_SECRET_KEY') }}"
        api_url: "{{ lookup('env', 'CLOUDSTACK_API_URL') }}"
      register: subnet

    - name: Deploy multiple VMs
      loop: "{{ range(1, num_vms + 1) | list }}"
      ngine_io.cloudstack.cs_instance:
        name: "{{ vm_name_prefix }}{{ '%02d' | format(item) }}.wezeshanet.local"
        service_offering: "Small Instance"
        template: "Ubuntu 22.04 LTS"
        zone: "Maryland"
        network: "{{ network.id }}"
        ip_address: auto
        api_key: "{{ lookup('env', 'CLOUDSTACK_API_KEY') }}"
        secret_key: "{{ lookup('env', 'CLOUDSTACK_SECRET_KEY') }}"
        api_url: "{{ lookup('env', 'CLOUDSTACK_API_URL') }}"
      register: vm_results

    - name: Assign a public IP to each VM
      loop: "{{ vm_results.results }}"
      ngine_io.cloudstack.cs_ip_address:
        vpc: "{{ subnet.id }}"
        api_key: "{{ lookup('env', 'CLOUDSTACK_API_KEY') }}"
        secret_key: "{{ lookup('env', 'CLOUDSTACK_SECRET_KEY') }}"
        api_url: "{{ lookup('env', 'CLOUDSTACK_API_URL') }}"
      register: public_ips

    - name: Add public IP to each VM
      loop: "{{ vm_results.results | zip(public_ips.results) | list }}"
      ngine_io.cloudstack.cs_staticnat:
        state: present
        ip_address: "{{ item.1.ipaddress }}"
        vm: "{{ item.0.id }}"
        api_key: "{{ lookup('env', 'CLOUDSTACK_API_KEY') }}"
        secret_key: "{{ lookup('env', 'CLOUDSTACK_SECRET_KEY') }}"
        api_url: "{{ lookup('env', 'CLOUDSTACK_API_URL') }}"

