---
- name: Set up CloudStack environment
  hosts: localhost
  gather_facts: no
  collections:
    - ngine_io.cloudstack

  vars:
    num_vms: 2
    vm_name_prefix: "brian-test"
    api_url: "{{ lookup('env', 'API_URL') }}"
    api_key: "{{ lookup('env', 'API_KEY') }}"
    api_secret: "{{ lookup('env', 'SECRET_KEY') }}"
    zone: "us-east-1a"
    template: "Ubuntu 22.04 LTS"
    service_offering: "Small Instance"
    network: "Compfinity"

  tasks:
    - name: Deploy multiple VMs
      ngine_io.cloudstack.cs_instance:
        name: "{{ vm_name_prefix }}{{ '%02d' | format(item) }}"
        service_offering: "{{ service_offering }}"
        template: "{{ template }}"
        zone: "{{ zone }}"
        network: "{{ network }}"
        api_key: "{{ api_key }}"
        api_secret: "{{ api_secret }}"
        api_url: "{{ api_url }}"
      loop: "{{ range(1, num_vms + 1) | list }}"
      register: vm_results

