---
- name: Set up CloudStack environment with VPC and Network
  hosts: localhost
  gather_facts: no
  collections:
    - ngine_io.cloudstack

  vars:
    num_vms: 2
    vm_name_prefix: "brian-test"
    api_url: "{{ lookup('env', 'API_URL') }}"
    api_key: "{{ lookup('env', 'API_KEY') }}"
    api_secret: "{{ lookup('env', 'SECRET_KEY') }}"
    zone: "us-east-1a"
    template: "Ubuntu 22.04 LTS"
    service_offering: "Small Instance"
    network: "BrianNetwork"
    vpc_name: "BrianVPC"
    vpc_cidr: "10.1.0.0/16"
    network_offering: "DefaultIsolatedNetworkOfferingWithSourceNatService"

  tasks:
    - name: Create VPC
      ngine_io.cloudstack.cs_vpc:
        name: "{{ vpc_name }}"
        cidr: "{{ vpc_cidr }}"
        api_key: "{{ api_key }}"
        api_secret: "{{ api_secret }}"
        zone: "{{ zone }}"
        api_url: "{{ api_url }}"
      register: vpc_result

    - name: Create Network in VPC
      ngine_io.cloudstack.cs_network:
        name: "{{ network }}"
        vpc: "{{ vpc_result.id }}"
        api_key: "{{ api_key }}"
        api_secret: "{{ api_secret }}"
        api_url: "{{ api_url }}"
        zone: "{{ zone }}"
      register: network_result

    - name: Deploy multiple VMs
      ngine_io.cloudstack.cs_instance:
        name: "{{ vm_name_prefix }}{{ '%02d' | format(item) }}"
        service_offering: "{{ service_offering }}"
        template: "{{ template }}"
        zone: "{{ zone }}"
        network: "{{ network_result.id }}"
        api_key: "{{ api_key }}"
        api_secret: "{{ api_secret }}"
        api_url: "{{ api_url }}"
      loop: "{{ range(1, num_vms + 1) | list }}"
      register: vm_results
