---
- name: Install and configure Zabbix agent on multiple servers
  hosts: all
  become: true
  vars:
    zabbix_server_ip: "172.16.6.2"
    autoregister_group: "compfinity,linux"

  tasks:
    - name: Install Zabbix agent
      package:
        name: zabbix-agent
        state: present

    - name: Configure Zabbix agent
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        line: "{{ item.line }}"
        create: true
      loop:
        - { line: "Server={{ zabbix_server_ip }}" }
        - { line: "ServerActive={{ zabbix_server_ip }}" }
        - { line: "Hostname={{ ansible_hostname }}" }
        - { line: "HostMetadata={{ autoregister_group }}" }

    - name: Restart Zabbix agent service
      service:
        name: zabbix-agent
        state: restarted

