---
- name: Deploy Multiple VMs
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    num_vms: 2

  tasks:
    - name: Create VMs
      vmware_guest:
        hostname: 172.16.254.31
        username: bchemweno@virtualweb.local
        password: Sinon1998!
        folder: /vm
        name: cf-pctest{{ '%02d' | format(vm_number) }}.compfinity.local
        state: present
        template: cf-pc02.ubuntu.template
        datacenter: Rockville Datacenter
        cluster: Gen14 Prod Cluster
        resource_pool: /Virtualweb/UAT 
        networks:
          - name: Compfinity Network
        validate_certs: no
      loop: "{{ range(1, num_vms + 1) | list }}"
      loop_control:
        loop_var: vm_number

