---
- name: Install and configure Zabbix agent
  hosts: all
  become: yes
  vars:
    zabbix_server_ip: "172.16.6.2"
    autoregister_group: "compfinity,linux"

  tasks:
    - name: Install Zabbix agent package
      apt:
        name: zabbix-agent
        state: present

    - name: Print ansible_hostname
      debug:
        msg: "The value of ansible_hostname is {{ ansible_hostname }}"

    - name: Configure Zabbix agent
      template:
        src: zabbix_agentd.conf.j2
        dest: /etc/zabbix/zabbix_agentd.conf
      vars:
        zabbix_server_ip: "{{ zabbix_server_ip }}"
        ansible_hostname: "{{ ansible_hostname }}"
        autoregister_group: "{{ autoregister_group }}"
      notify: restart zabbix-agent

  handlers:
    - name: restart zabbix-agent
      service:
        name: zabbix-agent
        state: restarted

