---
- name: Schedule and Reboot Windows Servers
  hosts: windows_servers
  collections:
    - ansible.windows
    - community.zabbix

  tasks:
    - name: Schedule reboot in vSphere
      vmware_guest:
        hostname: "vwr-vc8.virtualweb.local"
        username: "bchemweno@virtualweb.local"
        password: "Sinon1998!"
        validate_certs: no  # Set to yes if you have proper certificates installed
        name: "{{ inventory_hostname }}"  # Use Semaphore inventory hostname
        state: poweredon  # Ensure the VM is powered on
        hardware:
          boot_order:
            - network
            - disk
        wait_for_ip_address: yes  # Wait for VM to have an IP address
      delegate_to: localhost  # Run the task on the Ansible control machine

    - name: Set up Zabbix maintenance
      zabbix_maintenance:
        server_url: "http://172.16.6.2/zabbix/api_jsonrpc.php"
        login_user: "{{ semaphore_zabbix_user }}"
        login_password: "{{ semaphore_zabbix_password }}"
        state: present
        name: "B-UAT Server Reboot"
        host_names:
          - "{{ inventory_hostname }}"  # Use Semaphore inventory hostname
        time_periods:
          - start_time: "{{ lookup('pipe', 'date -d \"20:00\" +%s') }}"
            period: 3600
        validate_certs: no 
