---
- name: Schedule and Reboot Windows Servers
  hosts: windows_servers
  tasks:
    - name: Schedule reboot at 8 PM Kenyan time
      ansible.windows.win_scheduled_task:
        name: "Reboot"
        description: "Scheduled reboot at 8 PM Kenyan time"
        actions:
          - path: "C:\\Windows\\System32\\shutdown.exe"
            arguments: "/r /t 0"
        triggers:
          - type: daily
            start_boundary: "{{ 'now' | ansible.utils.date_time.ansible_datetime.iso8601 }}"
        username: "SYSTEM"
        state: present

    - name: Set up Zabbix maintenance
      community.zabbix.zabbix_maintenance:
        server_url: "http://zabbix_server_url"
        login_user: "zabbix_api_user"
        login_password: "zabbix_api_password"
        maintenance_name: "Server Reboot"
        maintenance_start_date: "{{ 'now' | ansible.utils.date_time.ansible_datetime.iso8601 }}"
        maintenance_period: "1h"
        maintenance_create_unavailable: true
        maintenance_tags:
          - "Windows Servers"
        state: present

    - name: Reboot Windows servers
      ansible.windows.win_reboot:
        msg: "Reboot initiated by Ansible"
        timeout: 600
