---
- name: Schedule and Reboot Windows Servers
  hosts: windows_servers
  tasks:
    - name: Schedule reboot at 8 PM Kenyan time
      community.windows.win_scheduled_task:
        name: "Reboot"
        description: "Scheduled reboot at 8 PM Kenyan time"
        actions:
          - path: "C:\\Windows\\System32\\shutdown.exe"
            arguments: "/r /t 0"
        triggers:
          - type: daily
            start_boundary: "{{ '2024-05-21T20:00:00' }}"  # Replace with the desired date and time
        username: "SYSTEM"
        state: present

    - name: Set up Zabbix maintenance
      community.zabbix.zabbix_maintenance:
        server_url: "http://172.16.6.2/zabbix/api_jsonrpc.php"
        login_user: "{{ semaphore_zabbix_user }}"
        login_password: "{{ semaphore_zabbix_password }}"
        state: present
        name: "B-UAT Server Reboot"
        host_names:
          - "{{ inventory_hostname }}"
        time_periods:
          - start_time: "{{ lookup('pipe', 'date -d \"20:00\" +%s') }}"
            period: 3600
        validate_certs: no

    - name: Reboot Windows servers
      community.windows.win_reboot:
        msg: "Reboot initiated by Ansible"
        timeout: 600
        reboot_timeout: 3600

